# Generated by Django 3.2.11 on 2022-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projecetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ima', models.ImageField(upload_to='im')),
                ('des', models.TextField()),
            ],
        ),
    ]
