# Generated by Django 3.2.11 on 2022-02-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=20)),
                ('ima2', models.ImageField(upload_to='pic')),
                ('des2', models.TextField()),
            ],
        ),
    ]
